package servent.message;

public enum MessageType {
	POISON,
	TOKEN,
	LAMPORT_REQUEST, LAMPORT_RELEASE, LAMPORT_REPLY,
	BOOTSTRAP_RESPONSE, BOOTSTRAP_ASK,
	ADD_ME, UPDATE_STATE, WELCOME,
	PING, PONG,
	IS_OK, NOT_OK, OK,
	FILE_ASK, FILE_TELL,
	SUZUKI_REQUEST, SUZUKI_REPLY, SUZUKI_RELEASE,
	GIVE_BACKUP
}
